# @package _global_

defaults:
  - _self_
  - datamodule: cifar10.yaml # choose datamodule with `test_dataloader()` for evaluation
  - model: cifar10.yaml
  - logger: null
  - trainer: default.yaml
  - paths: default.yaml
  - extras: default.yaml
  - hydra: default.yaml

task_name: "eval"

tags: ["dev"]

# passing checkpoint path is necessary for evaluation
ckpt_path: C:\Users\katta\Desktop\MLOPS\Week2\assignmrnt_re\cifar10hydralightning\logs\train\runs\2022-09-11_10-09-32\checkpoints\epoch_002.ckpt
